version: 2
jobs:
  test1:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      - run:
          name: Test1 
          command: |
                   echo "Hello from job test one"

  test2:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Test2
          command: |
                   echo "Hello from job test2"


workflows:
  version: 2
  test1-test2:
    jobs:
      - test1:
          filters:
            tags:
              only:
                - v1.0.0
      - test2:
          filters:
            tags:
              only:
                - v1.0.1
