version: 2.1

workspace_root: &workspace_root
  /tmp/workspace
  

jobs:
  test1:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      - run:
          name: Test1 
          command: |
                   echo "Hello from job test one"
                   echo $CIRCLE_PROJECT_USERNAME
      - run:
          name: Test GH
          command: |
                   mkdir test 
      - run:
          name: Export CIRCLE_TAG for use in test2
          command: |
                   import urllib.request, json, os
                   with urllib.request.urlopen("https://api.github.com/repos/eremija/nextjs/releases") as url:
                       data = json.loads(url.read().decode())
                       git_tag = data[0]["tag_name"]

                   os.environ["CIRCLE_TAG"]=str(git_tag)

      - persist_to_workspace:
          root: *workspace_root
          path: .


  test2:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Test2
          command: |
                   echo "Hello from job test2"
                   echo $CIRCLE_TAG


workflows:
  version: 2
  test1-test2:
    jobs:
      - test1:
          filters:
            tags:
              only: /^v1\.4\.0/ 
      - test2
#          filters:
#            tags:
#              only:
#                - v1.0.1
