version: 2.1
jobs:
  test1:
    docker:
      - image: circleci/python:latest

    steps:
      # Checkout the git repo
      - checkout
      - run:
          name: Test1 
          command: |
                   echo "Hello from job test1"

  test2:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Test2
          command: |
                   echo "Hello from job test2"


workflows:
  version: 2.1
  test1-test2:
    jobs:
      - test1
      - test2
