version: 2.1

workspace_root: &workspace_root
  /tmp/workspace

jobs:
  test1:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      
      - run:
          name: Export CIRCLE_TAG for use in test2
          command: |
                   export CIRCLE_TAG=`git describe --tags --abbrev=0`
                   mkdir -p /tmp/workspace/scripts
                   env | grep CIRCLE_TAG > .env
                   cp .env /tmp/workspace/scripts/

      - run:
          name: Check if CIRCLE_TAG is present
          command: |
                   env

      - persist_to_workspace:
          root: *workspace_root
          paths: scripts

  test2:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Test2
          command: |
                   echo "Hello from job test2"
                   source /tmp/workspace/scripts/.env
                   echo $CIRCLE_TAG


workflows:
  version: 2
  test1-test2:
    jobs:
      - test1:
          filters:
            tags:
              only: /^v1\.4\.0/ 
      - test2
#          filters:
#            tags:
#              only:
#                - v1.0.1
