version: 2.1

workspace_root: &workspace_root
  /tmp/workspace

jobs:
  test1:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout
      - run:
          name: Test1 
          command: |
                   echo "Hello from job test one"
                   echo $CIRCLE_PROJECT_USERNAME
      
      - run:
          name: Export CIRCLE_TAG for use in test2
          command: |
                   mkdir -p /tmp/workspace/scripts
                   cp releases.py /tmp/workspace/scripts
                   python releases.py 

      - run:
          name: Check if CIRCLE_TAG is present
          command: |
                   echo $CIRCLE_TAG

      - persist_to_workspace:
          root: *workspace_root
          path: scripts

  test2:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - run:
          name: Test2
          command: |
                   echo "Hello from job test2"
                   echo $CIRCLE_TAG


workflows:
  version: 2
  test1-test2:
    jobs:
      - test1:
          filters:
            tags:
              only: /^v1\.4\.0/ 
      - test2
#          filters:
#            tags:
#              only:
#                - v1.0.1
