version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  aws-s3: circleci/aws-s3@1.0.15

workspace_root: &workspace_root
  /tmp/workspace

parameters:
  triggered-by-cms:
    type: boolean
    default: false

jobs:
  test1:
    docker:
      - image: circleci/python:latest

    steps:
      - checkout

      - run:
          name: Identify build source
          command: |
            if [ "${CIRCLECI_USERNAME}" == "" ]; then
              echo "Triggered by publishing content on CMS."
            else
              echo "Normal build."
            fi


      - run:
          name: Verify the ENV var is present
          command: |
                   env

      - run:
          name: Export CIRCLE_TAG for use in test2
          command: |
                   export CIRCLE_TAG=`git describe --tags --abbrev=0`
                   mkdir -p /tmp/workspace/scripts
                   env | grep CIRCLE_TAG

      - persist_to_workspace:
          root: *workspace_root
          paths: scripts

  test2:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Test2
          command: |
                   echo "Hello from job test2"

workflows:
  version: 2
  test1:
    jobs:
      - test1:
          filters:
            branches:
              only:
                - master
  test2:
    when: << pipeline.parameters.triggered-by-cms >>
    jobs:
      - test2:
          filters:
            branches:
              only:
                - production
  test1-test2:
    jobs:
      - test1
      - test2
