#!/bin/bash

echo "Running the job using CircleCI API..."

curl -u fa99e0d24aea48217e311f015cb7999f5d086b0d: \
     -d build_parameters[CIRCLE_JOB]=test1 \
     https://circleci.com/api/v1.1/project/github/eremija/nextjs/tree/master &&
echo "`date +%m-%d-%Y`" >> VERSION
