#!/bin/bash

BRANCH=master

#target_branch="master"
#working_tree="PATH_TO_DEPLOY"

#while read oldrev newrev refname
#do
#    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
#    if [ -n "$branch" ] && [ "$target_branch" == "$branch" ]; then
#    
#       GIT_WORK_TREE=$working_tree git checkout $target_branch -f
#       NOW=$(date +"%Y%m%d-%H%M")
#       git tag release_$NOW $target_branch
#    
#       echo "   /==============================="
#       echo "   | DEPLOYMENT COMPLETED"
#       echo "   | Target branch: $target_branch"
#       echo "   | Target folder: $working_tree"
#       echo "   | Tag name     : release_$NOW"
#       echo "   \=============================="
#    fi
#done
echo "Running the job using CircleCI API..."

while read oldrev newrev ref
do
    # only checking out the master (or whatever branch you would like to deploy)
    if [[ $ref = refs/heads/$BRANCH ]];
    then
        curl -u fa99e0d24aea48217e311f015cb7999f5d086b0d: -d build_parameters[CIRCLE_JOB]=test1 https://circleci.com/api/v1.1/project/github/eremija/nextjs/tree/master &&
        echo "`date +%m-%d-%Y`" > ../VERSION
    else
        echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
    fi
done
